### ISSUE TITLE
Random Frame Access Without Preloading the Entire File?

### ISSUE THREAD

**Issue by Erotemic** [dmlc/decord#80]
I'm wondering if the following feature is possible. 

I'd like to be able to randomly access any frame without having to load the entire file into disk. Currently it seems like decord loads all of the video bytes into memory when you create an instace of `decord.VideoReader`, and then it lets you load the data. 

I have a use case where I have thousands of video file, and I only need to extract a few specific frames from each video. Instead of loading the entire file into memory and then randomly decoding those specific frames (which it seems decord already does well), is it possible for decord to just open a handle to the file (without reading the entire thing), seek to the nearest iframe, and then use the subsequent b/p frames to construct the requested frame without necessarily having to read the entire thing? 

Even in the case where the video doesn't have intermediate iframes, shouldn't it still be possible to extract the first frame of a 4GB video without loading all 4GB into memory?

**Comment by zhreshold** [comment]
@Erotemic "Instead of loading the entire file into memory and then randomly decoding those specific frames (which it seems decord already does well), is it possible for decord to just open a handle to the file (without reading the entire thing), seek to the nearest iframe, and then use the subsequent b/p frames to construct the requested frame without necessarily having to read the entire thing?" this is what `decord` is doing right now, it does not load the entire file into memory.

**Comment by Erotemic** [comment]
Huh, I was benchmarking, and it didn't look like that was happening, but I likely made a mistake. Sorry for the noise.
